set_property PACKAGE_PIN R2 [get_ports pin_clk_i]
set_property PACKAGE_PIN C18 [get_ports pin_arst_n_i]
set_property PACKAGE_PIN V12 [get_ports pin_rx_i]
set_property PACKAGE_PIN R12 [get_ports pin_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports pin_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports pin_rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports pin_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports pin_arst_n_i]

create_clock -period 10.000 -name pin_clk_i -waveform {0.000 5.000} [get_ports pin_clk_i]
