include(${CMAKE_CURRENT_LIST_DIR}/cpu_config.cmake)

set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES OUTPUT_NAME ${CMAKE_PROJECT_NAME}.elf)

add_custom_target(elf2bin DEPENDS ${CMAKE_PROJECT_NAME} COMMAND ${CMAKE_OBJCOPY} -O binary ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.elf ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.bin)
add_custom_target(elf2mem DEPENDS elf2bin COMMAND cat ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.bin | hexdump -v -e '\"%08x\\n\"' > ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.mem)
add_custom_target(elf2debug DEPENDS ${CMAKE_PROJECT_NAME} COMMAND ${CMAKE_OBJDUMP} --source ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.elf > ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.debug)
add_custom_target(show_size DEPENDS ${CMAKE_PROJECT_NAME} COMMAND ${CMAKE_SIZE} --format=berkeley ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.elf)

add_custom_target(ghdl DEPENDS elf2mem COMMAND make -C ${CMAKE_CURRENT_SOURCE_DIR}/../../rtl/proj/ghdl run
    INIT_FILE=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.mem
    EXECUTE_BYPASS=${EXECUTE_BYPASS}
    MEMORY_BYPASS=${MEMORY_BYPASS}
    WRITEBACK_BYPASS=${WRITEBACK_BYPASS}
    REGFILE_BYPASS=${REGFILE_BYPASS}
    FULL_BARREL_SHIFTER=${FULL_BARREL_SHIFTER}
    SHIFTER_EARLY_INJECTION=${SHIFTER_EARLY_INJECTION}
    STOP_TIME=${STOP_TIME}
)
add_custom_target(modelsim DEPENDS elf2mem COMMAND make -C ${CMAKE_CURRENT_SOURCE_DIR}/../../rtl/proj/modelsim run
    INIT_FILE=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_PROJECT_NAME}.mem
    EXECUTE_BYPASS=${EXECUTE_BYPASS}
    MEMORY_BYPASS=${MEMORY_BYPASS}
    WRITEBACK_BYPASS=${WRITEBACK_BYPASS}
    REGFILE_BYPASS=${REGFILE_BYPASS}
    FULL_BARREL_SHIFTER=${FULL_BARREL_SHIFTER}
    SHIFTER_EARLY_INJECTION=${SHIFTER_EARLY_INJECTION}
    STOP_TIME=${STOP_TIME}
)
